networks:
  home-net:
    external: true

services:
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8050:80
    environment:
      PMA_HOSTS: mysql,mysql-3e7cbfc8-blogit.l.aivencloud.com:23426
      PMA_PORT: 3306, 23426
    networks:
      - home-net
