[database.apim_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/apim_db?useSSL=false"
username = "wso2"
password = "wso2_password"
driver = "com.mysql.cj.jdbc.Driver"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/shared_db?useSSL=false"
username = "wso2"
password = "wso2_password"
driver = "com.mysql.cj.jdbc.Driver"

[super_admin]
username = "admin"
password = "admin"
